# Generated by Django 6.0.2 on 2026-02-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Luxury', 'Luxury'), ('Sport', 'Sport'), ('Casual', 'Casual'), ('Smart', 'Smart'), ('Vintage', 'Vintage')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='watches')),
            ],
        ),
    ]
